name: Scheduled Job

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/1 * * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    env:
      PSQL_USER: postgres
      PSQL_HOST: 34.92.22.202
      PSQL_DATABASE: postgres
      PSQL_PASSWORD: Highfive5+
      PSQL_PORT: 5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: echo "running"
      - run: npm install
      - run: node db/test
