name: Scheduled Job

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/1 * * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: echo "running"
      - run: npm install
      - run: node db/test
